name: CMake on Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "export PATH=$PATH:${{ github.workspace }}/depot_tools" >> $GITHUB_ENV

    - name: Cache depot_tools
      uses: actions/cache@v3
      with:
        path: depot_tools
        key: ${{ runner.os }}-depot_tools-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-depot_tools-

    - name: Cache CMake build
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Cache CMake dependencies
      uses: actions/cache@v3
      with:
        path: |
          .cache
        key: ${{ runner.os }}-cmake-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Install libreadline-dev
      run: sudo apt-get install -y libreadline-dev

    - name: Build project
      working-directory: ${{ github.workspace }}
      run: ./build.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/build

  lexer-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/build

      - name: Make LexerTest Executable
        run: chmod +x ${{ github.workspace }}/build/LexerTest

      - name: Run Lexer Test
        working-directory: ${{ github.workspace }}/build
        run: ./LexerTest

  parser-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/build

    - name: Make ParserTest Executable
      run: chmod +x ${{ github.workspace }}/build/ParserTest

    - name: Run Parser Test
      working-directory: ${{ github.workspace }}/build
      run: ./ParserTest

  typechecker-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/build

    - name: Make TypeCheckerTest Executable
      run: chmod +x ${{ github.workspace }}/build/TypeCheckerTest

    - name: Run TypeChecker Test
      working-directory: ${{ github.workspace }}/build
      run: ./TypeCheckerTest

  codegen-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}/build

    - name: Make CodegenTest Executable
      run: chmod +x ${{ github.workspace }}/build/CodegenTest

    - name: Run Codegen Test
      working-directory: ${{ github.workspace }}/build
      run: ./CodegenTest

